In [ ]:
import pandas as pd

# **SERIES**

In [ ]:
s = pd.Series( [10,20,30,40,50] )
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.values

array([10, 20, 30, 40, 50])

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
print(s.name)

None

In [ ]:
s.name = "numbers"
s

0    10
1    20
2    30
3    40
4    50
Name: numbers, dtype: int64

In [ ]:
s.name

'numbers'

# **INDEXING**

In [ ]:
s[0]

np.int64(10)

In [ ]:
s[0:3]

0    10
1    20
2    30
Name: numbers, dtype: int64

In [ ]:
s[2:]

2    30
3    40
4    50
Name: numbers, dtype: int64

In [ ]:
# iloc -> location based indexing
s.iloc[3]

np.int64(40)

In [ ]:
s.iloc[ [1,4] ]

1    20
4    50
Name: numbers, dtype: int64

In [ ]:
# changing index values
s.name = "calories"
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [ ]:
values = ["apples", "mangoes" , "grapes" ,"papaya","cherry"]
s.index = values
s

apples     10
mangoes    20
grapes     30
papaya     40
cherry     50
Name: calories, dtype: int64

In [ ]:
s['apples']

np.int64(10)

In [ ]:
s.iloc['apples']  # -> iloc can't be used here because now its not a location anymore

TypeError: Cannot index by location index with a non-integer key

In [ ]:
# loc function -> it's a label based indexing
s.loc['apples']

np.int64(10)

In [ ]:
# in  label based indexing the start and stop both values are included
s.loc['mangoes' : 'papaya']

mangoes    20
grapes     30
papaya     40
Name: calories, dtype: int64

In [ ]:
# get multiple values
s.loc[ ['apples' , 'cherry'] ]

apples    10
cherry    50
Name: calories, dtype: int64

# create series from dictionary

In [ ]:
fruit_protein = {
    "avacado":2.4 ,
    "guava":4.1,
    "oranges":3.2,
    "apples":8.1,
    "kiwi":4.2,
    "pomegranate":6.4,
    "mango":6.3,
    "cherries":7.2,
    "blackberries":2.2,
    "banana":6.4
}
s2 = pd.Series(fruit_protein , name = "protein")
s2

avacado         2.4
guava           4.1
oranges         3.2
apples          8.1
kiwi            4.2
pomegranate     6.4
mango           6.3
cherries        7.2
blackberries    2.2
banana          6.4
Name: protein, dtype: float64

In [ ]:
s2 > 3

avacado         False
guava            True
oranges          True
apples           True
kiwi             True
pomegranate      True
mango            True
cherries         True
blackberries    False
banana           True
Name: protein, dtype: bool

In [ ]:
s2[s2 > 3]

guava          4.1
oranges        3.2
apples         8.1
kiwi           4.2
pomegranate    6.4
mango          6.3
cherries       7.2
banana         6.4
Name: protein, dtype: float64

In [ ]:
# LOGICAL OPERATORS

# AND
s2 [ (s2 > 3) & (s2 < 8) ]

guava          4.1
oranges        3.2
kiwi           4.2
pomegranate    6.4
mango          6.3
cherries       7.2
banana         6.4
Name: protein, dtype: float64

In [ ]:
# OR
s2 [ (s2 > 3) | (s2 < 8) ]

avacado         2.4
guava           4.1
oranges         3.2
apples          8.1
kiwi            4.2
pomegranate     6.4
mango           6.3
cherries        7.2
blackberries    2.2
banana          6.4
Name: protein, dtype: float64

In [ ]:
# NOT
s2 [ ~ (s2 > 3) ]

avacado         2.4
blackberries    2.2
Name: protein, dtype: float64

In [ ]:
# modifying the series
s2['kiwi']=5.3
s2

avacado         2.4
guava           4.1
oranges         3.2
apples          8.1
kiwi            5.3
pomegranate     6.4
mango           6.3
cherries        7.2
blackberries    2.2
banana          6.4
Name: protein, dtype: float64

In [ ]:
# extra

import numpy as np
ser = pd.Series ( ['a' , np.nan , 1 , np.nan , 2] )
ser.notnull().sum()

# extra

np.int64(3)

# **DATAFRAME**

In [ ]:
data = {
    "Name":["alice","bob","charlie","david","eve","alice"],
    "Age":[25 , 30 , 20 , np.nan , 29 , 25] ,                                        # nan -> not  anumber
    "Department":["HR","IT","Finance","IT","HR","HR"],
    "Salary":[50000 , 30000 , 60000 , 80000 , np.nan , 50000]
}
data

{'Name': ['alice', 'bob', 'charlie', 'david', 'eve', 'alice'],
 'Age': [25, 30, 20, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 30000, 60000, 80000, nan, 50000]}

In [ ]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    alice  25.0         HR  50000.0
1      bob  30.0         IT  30000.0
2  charlie  20.0    Finance  60000.0
3    david   NaN         IT  80000.0
4      eve  29.0         HR      NaN
5    alice  25.0         HR  50000.0

In [ ]:
 # df.head() -> by default returns first 5 rows
print( df.head() )
print()
print(df.head(2))

      Name   Age Department   Salary
0    alice  25.0         HR  50000.0
1      bob  30.0         IT  30000.0
2  charlie  20.0    Finance  60000.0
3    david   NaN         IT  80000.0
4      eve  29.0         HR      NaN

    Name   Age Department   Salary
0  alice  25.0         HR  50000.0
1    bob  30.0         IT  30000.0

In [ ]:
# df.tail() -> by default returns last 5 rows
print( df.tail() )
print()
print(df.tail(2))

      Name   Age Department   Salary
1      bob  30.0         IT  30000.0
2  charlie  20.0    Finance  60000.0
3    david   NaN         IT  80000.0
4      eve  29.0         HR      NaN
5    alice  25.0         HR  50000.0

    Name   Age Department   Salary
4    eve  29.0         HR      NaN
5  alice  25.0         HR  50000.0

In [ ]:
# iloc
df.iloc[2:4]

      Name   Age Department   Salary
2  charlie  20.0    Finance  60000.0
3    david   NaN         IT  80000.0

In [ ]:
# loc
df.loc[1:3 , ["Department" , "Age"] ]

  Department   Age
1         IT  30.0
2    Finance  20.0
3         IT   NaN

In [ ]:
# accesing only some coloumns
df[ ["Age","Department"] ]

    Age Department
0  25.0         HR
1  30.0         IT
2  20.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [ ]:
# drop -> remove a particular row or colm from the dataframe
df.drop(0) # to remove a row

      Name   Age Department   Salary
1      bob  30.0         IT  30000.0
2  charlie  20.0    Finance  60000.0
3    david   NaN         IT  80000.0
4      eve  29.0         HR      NaN
5    alice  25.0         HR  50000.0

In [ ]:
df.drop("Age" , axis = 1) # to remove a col

      Name Department   Salary
0    alice         HR  20000.0
1      bob         IT  30000.0
2  charlie    Finance  60000.0
3    david         IT  80000.0
4      eve         HR      NaN
5    alice         HR  50000.0

In [ ]:
df

      Name   Age Department   Salary
0    alice  25.0         HR  50000.0
1      bob  30.0         IT  30000.0
2  charlie  20.0    Finance  60000.0
3    david   NaN         IT  80000.0
4      eve  29.0         HR      NaN
5    alice  25.0         HR  50000.0

In [ ]:
# to remove data from the original  dataframe
# df.drop("Age" , axis = 1 , inplace = True)
# print(df)

In [ ]:
# to find the number of rows and colms
df.shape

(6, 4)

In [ ]:
# to get information about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
# to give statistical info about data
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   25.800000  54000.000000
std     3.962323  18165.902125
min    20.000000  30000.000000
25%    25.000000  50000.000000
50%    25.000000  50000.000000
75%    29.000000  60000.000000
max    30.000000  80000.000000

In [ ]:
# broadcasting
df["Salary"] = df["Salary"] + 5000

In [ ]:
df["Salary"]

0    55000.0
1    35000.0
2    65000.0
3    85000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [ ]:
# rename a coloumn
df.rename( columns = {"Department" : "Dept"} , inplace = True )

In [ ]:
df

      Name   Age     Dept   Salary
0    alice  25.0       HR  55000.0
1      bob  30.0       IT  35000.0
2  charlie  20.0  Finance  65000.0
3    david   NaN       IT  85000.0
4      eve  29.0       HR      NaN
5    alice  25.0       HR  55000.0

In [ ]:
# check unique values in a particular coloumn
print ( df["Dept"].unique() )
print()
print ( df["Name"].unique() )

['HR' 'IT' 'Finance']

['alice' 'bob' 'charlie' 'david' 'eve']

In [ ]:
# distribution of data in a coloumn
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [ ]:
# add a new coloumn
df["Promoted_Salary"] = df["Salary"]*10

In [ ]:
df

      Name   Age     Dept   Salary  Promoted_Salary
0    alice  25.0       HR  55000.0         550000.0
1      bob  30.0       IT  35000.0         350000.0
2  charlie  20.0  Finance  65000.0         650000.0
3    david   NaN       IT  85000.0         850000.0
4      eve  29.0       HR      NaN              NaN
5    alice  25.0       HR  55000.0         550000.0

data cleaning

In [ ]:
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted_Salary    1
dtype: int64

In [ ]:
# to drop the rows having null values
df.dropna()
# or df.dropna(how = 'any')  -> any row that had any null value
# df.drop(how = 'all')  -> delte only those rows where all values are nulll

      Name   Age     Dept   Salary  Promoted_Salary
0    alice  25.0       HR  55000.0         550000.0
1      bob  30.0       IT  35000.0         350000.0
2  charlie  20.0  Finance  65000.0         650000.0
5    alice  25.0       HR  55000.0         550000.0

In [ ]:
df

      Name   Age     Dept   Salary  Promoted_Salary
0    alice  25.0       HR  55000.0         550000.0
1      bob  30.0       IT  35000.0         350000.0
2  charlie  20.0  Finance  65000.0         650000.0
3    david   NaN       IT  85000.0         850000.0
4      eve  29.0       HR      NaN              NaN
5    alice  25.0       HR  55000.0         550000.0

In [ ]:
# replace na values with some other values
df.fillna(0)

      Name   Age     Dept   Salary  Promoted_Salary
0    alice  25.0       HR  55000.0         550000.0
1      bob  30.0       IT  35000.0         350000.0
2  charlie  20.0  Finance  65000.0         650000.0
3    david   0.0       IT  85000.0         850000.0
4      eve  29.0       HR      0.0              0.0
5    alice  25.0       HR  55000.0         550000.0

In [ ]:
# to fill the ( na ) value with mean
df["Age"].fillna(  df["Age"].mean() )

0    25.0
1    30.0
2    20.0
3    25.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
# to fill the ( na ) value with median
df["Salary"].fillna(  df["Salary"].median() )

0    55000.0
1    35000.0
2    65000.0
3    85000.0
4    55000.0
5    55000.0
Name: Salary, dtype: float64

In [ ]:
# fillna -> forward fill and backward fill
# forward fill :  top to botton (top value will be replaced with the just next missing value)
# backward fill : bottom to top (bottom value will be replaced with the just bottom past value)

In [ ]:
# backward fill
df["Age"].fillna(method = "bfill" )

/tmp/ipykernel_9373/912574474.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill" )

0    25.0
1    30.0
2    20.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
# forward fill
df["Age"].fillna(method = "ffill" )

/tmp/ipykernel_9373/399504200.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill" )

0    25.0
1    30.0
2    20.0
3    20.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
# to change the name of a student
df["Name"].replace( "Charlie","Rose")

0      alice
1        bob
2    charlie
3      david
4        eve
5      alice
Name: Name, dtype: object

In [ ]:
# if to change the name in the original dataset also
df["Name"] = df["Name"].replace( "charlie","Rose")

In [ ]:
df

    Name   Age     Dept   Salary  Promoted_Salary
0  alice  25.0       HR  55000.0         550000.0
1    bob  30.0       IT  35000.0         350000.0
2   Rose  20.0  Finance  65000.0         650000.0
3  david   NaN       IT  85000.0         850000.0
4    eve  29.0       HR      NaN              NaN
5  alice  25.0       HR  55000.0         550000.0

dealing with duplicate values

In [ ]:
# duplicated()  -> it will return the second duplicated value
df_dup = df[ df.duplicated() ]
df_dup

    Name   Age Dept   Salary  Promoted_Salary
5  alice  25.0   HR  55000.0         550000.0

In [ ]:
df_dup = df[ df.duplicated( keep = 'first' ) ] # by default it takes the value as keep = 'first
df_dup

    Name   Age Dept   Salary  Promoted_Salary
5  alice  25.0   HR  55000.0         550000.0

In [ ]:
df_dup = df[ df.duplicated( keep = 'last' ) ]  # it works from bottom to top
df_dup

    Name   Age Dept   Salary  Promoted_Salary
0  alice  25.0   HR  55000.0         550000.0

In [ ]:
# to remove the duplicate values
df = df.drop_duplicates()

In [ ]:
df

    Name   Age     Dept   Salary  Promoted_Salary
0  alice  25.0       HR  55000.0         550000.0
1    bob  30.0       IT  35000.0         350000.0
2   Rose  20.0  Finance  65000.0         650000.0
3  david   NaN       IT  85000.0         850000.0
4    eve  29.0       HR      NaN              NaN

INVALID VALUES

In [ ]:
df["Promoted_Salary"] = df["Promoted_Salary"].apply( lambda x : x/10 if x >= 650000 else x)

/tmp/ipykernel_9373/2233957902.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Promoted_Salary"] = df["Promoted_Salary"].apply( lambda x : x/10 if x >= 650000 else x)

In [ ]:
df

    Name   Age     Dept   Salary  Promoted_Salary
0  alice  25.0       HR  55000.0         550000.0
1    bob  30.0       IT  35000.0         350000.0
2   Rose  20.0  Finance  65000.0          65000.0
3  david   NaN       IT  85000.0          85000.0
4    eve  29.0       HR      NaN              NaN

In [ ]:
# if we have a string input of name ad first name and last name then it can be split into two coloumns namely FIRST NAME and LAST NAME using split function of string
name = "alice_fernedes"
df[ ['first_name','last_name'] ] = df["name"].str.split("_")

KeyError: 'name'

apply and lambda

In [ ]:
# these help the change the single entries in a string
def multiplying_age(x):
  return x*2

df["Age"] = df["Age"].apply( multiplying_age )

# or it can also be written as below

# df["Age"] = df["Age"].apply(lambda x : x*2)

/tmp/ipykernel_9373/1090246297.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply( multiplying_age )

In [ ]:
df

    Name   Age     Dept   Salary  Promoted_Salary
0  alice  50.0       HR  55000.0         550000.0
1    bob  60.0       IT  35000.0         350000.0
2   Rose  40.0  Finance  65000.0          65000.0
3  david   NaN       IT  85000.0          85000.0
4    eve  58.0       HR      NaN              NaN

In [ ]:
# converting ages back to the original values
df["Age"] = df["Age"].apply(lambda x : x/2)

/tmp/ipykernel_9373/3780771634.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(lambda x : x/2)

In [ ]:
df

    Name   Age     Dept   Salary  Promoted_Salary
0  alice  25.0       HR  55000.0         550000.0
1    bob  30.0       IT  35000.0         350000.0
2   Rose  20.0  Finance  65000.0          65000.0
3  david   NaN       IT  85000.0          85000.0
4    eve  29.0       HR      NaN              NaN

JOINS AND MERGES

In [ ]:
# JOINS = LEFT JOIN , RIGHT JOIN , OUTER JOIN , INNER JOIN
department_inf0 = {
    "Dept":['HR','IT','FINANCE'],
    "Location":['NEW YORK','SAN FRANCISCO','CHICAGO'],
    "Manager":['LAIRA','STEVE','NINA']
}
df2 = pd.DataFrame(department_inf0)

In [ ]:
df2

      Dept       Location Manager
0       HR       NEW YORK   LAIRA
1       IT  SAN FRANCISCO   STEVE
2  FINANCE        CHICAGO    NINA

In [ ]:
# to combine df and df2 -> CONCAT function
pd.concat( [df,df2] )

    Name   Age     Dept   Salary  Promoted_Salary       Location Manager
0  alice  25.0       HR  55000.0         550000.0            NaN     NaN
1    bob  30.0       IT  35000.0         350000.0            NaN     NaN
2   Rose  20.0  Finance  65000.0          65000.0            NaN     NaN
3  david   NaN       IT  85000.0          85000.0            NaN     NaN
4    eve  29.0       HR      NaN              NaN            NaN     NaN
0    NaN   NaN       HR      NaN              NaN       NEW YORK   LAIRA
1    NaN   NaN       IT      NaN              NaN  SAN FRANCISCO   STEVE
2    NaN   NaN  FINANCE      NaN              NaN        CHICAGO    NINA

In [ ]:
# if to merge the dataframes coloumn wise
pd.concat( [df,df2] , axis=1)

,Name,Age,Dept,Salary,Promoted_Salary,Dept,Location,Manager
0,alice,25.0,HR,55000.0,550000.0,HR,NEW YORK,LAIRA
1,bob,30.0,IT,35000.0,350000.0,IT,SAN FRANCISCO,STEVE
2,Rose,20.0,Finance,65000.0,65000.0,FINANCE,CHICAGO,NINA
3,david,NaN,IT,85000.0,85000.0,NaN,NaN,NaN
4,eve,29.0,HR,NaN,NaN,NaN,NaN,NaN

In [ ]:
# MERGE -> TO MERGE THE DATAFRAMES ON A COMMON COLOUMN
pd.merge( df , df2 ,on = 'Dept' )

    Name   Age Dept   Salary  Promoted_Salary       Location Manager
0  alice  25.0   HR  55000.0         550000.0       NEW YORK   LAIRA
1    bob  30.0   IT  35000.0         350000.0  SAN FRANCISCO   STEVE
2  david   NaN   IT  85000.0          85000.0  SAN FRANCISCO   STEVE
3    eve  29.0   HR      NaN              NaN       NEW YORK   LAIRA

# IMPORTING FILE

In [ ]:
data = pd.read_csv("Student_Dataset_!.csv")

In [ ]:
data.head()

      Name   Age Department  Marks  percentage   Id
0    Alice  20.0         CS   85.0          90  241
1      Bob  21.0         IT   78.0          70  456
2  Charlie  19.0        ECE   92.0          60  235
3    David  22.0    Finance   70.0          75  485
4      Eve   NaN         HR   88.0          85  695

In [ ]:
data.tail()

     Name   Age Department  Marks  percentage   Id
45   Uday  22.0         CS   79.0          84  569
46  Varun  23.0         IT   88.0          28  478
47  Waris  20.0        ECE   90.0          99  256
48  Yukti   NaN    Finance   75.0          46  325
49   Zoya  21.0         HR   93.0          50  in

In [ ]:
data.shape

(50, 6)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        50 non-null     object
 1   Age         45 non-null     float64
 2   Department  50 non-null     object
 3   Marks       49 non-null     float64
 4   percentage  50 non-null     int64
 5   Id          50 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 2.5+ KB

In [ ]:
# suppose if we have a coloumn named data_and_time having datatype as object  ->  now it is to be cnvted into date time
data["data"] = pd.to_datetime( data["date"] )